export const CONFIG = {
  SEARCH_DEBOUNCE_MS: 300,
  MAP_DEFAULT_ZOOM: 12,
  MAP_MAX_VISIBLE_MARKERS: 100,
  BOOKING_POLL_INTERVAL_MS: 5000,
  BOOKING_SAGA_TIMEOUT_MS: 60000,
  CONFLICT_RETRY_MAX: 3,
  CONFLICT_RETRY_BASE_MS: 1000,
  TOKEN_REFRESH_THRESHOLD_MS: 5 * 60 * 1000,
  IMAGE_CACHE_SIZE_MB: 200,
  PAGINATION_DEFAULT_LIMIT: 20,
} as const;
